[build]
  publish = "dist"
  command = "npm run generate"
[build.environment]
  NODE_VERSION = "11"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"